### PR TITLE
Added sample rust actix server

### PR DESCRIPTION
**Pull request by programmersoham**

### CODE REVIEW

**Review by idagelic — CHANGES_REQUESTED** [review]
Please signoff the commit
```
git commit --amend --signoff
git push -f
```

**Comment by programmersoham** [comment]
Hey @idagelic , I messed up trying to rebase to sign off all the commits. The PR got Closed Accidentally. I am really sorry for this. Please help.

**Comment by idagelic** [comment]
@programmersoham It's okay, you can reopen it. You may also do a signoff on the last commit only (steps above), and I will squash them, no worries.

**Comment by programmersoham** [comment]
I am not able to reopen this.

**Comment by programmersoham** [comment]
Repening

**Comment by idagelic** [comment]
@programmersoham Ah, I see, you force pushed the changes. You will need to create a separate PR identical to the way it was before, just call the two mentioned commands to complete the signoff

**Pull request closed without merging**
